version: '3'

services:
    web:
      build:
        context: .
        dockerfile: DockerFile
      ports:
        - "5000:5000"
      volumes:
        - ./data:/app/data
      depends_on:
        - mongodb
      

    mongodb:
      image: mongo:latest
      volumes:
        - ./data:/data/db
      environment:
        - MONGO_INITDB_DATABASE=DigitalAirlines
      

